//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUT.UI.BonusProjectorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BonusProjectorService.IBonusProjector")]
    public interface IBonusProjector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonusProjector/GetExpectedBonus", ReplyAction="http://tempuri.org/IBonusProjector/GetExpectedBonusResponse")]
        double GetExpectedBonus(double employeeCurrentSalary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonusProjector/GetExpectedBonus", ReplyAction="http://tempuri.org/IBonusProjector/GetExpectedBonusResponse")]
        System.Threading.Tasks.Task<double> GetExpectedBonusAsync(double employeeCurrentSalary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBonusProjectorChannel : SUT.UI.BonusProjectorService.IBonusProjector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BonusProjectorClient : System.ServiceModel.ClientBase<SUT.UI.BonusProjectorService.IBonusProjector>, SUT.UI.BonusProjectorService.IBonusProjector {
        
        public BonusProjectorClient() {
        }
        
        public BonusProjectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BonusProjectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonusProjectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonusProjectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetExpectedBonus(double employeeCurrentSalary) {
            return base.Channel.GetExpectedBonus(employeeCurrentSalary);
        }
        
        public System.Threading.Tasks.Task<double> GetExpectedBonusAsync(double employeeCurrentSalary) {
            return base.Channel.GetExpectedBonusAsync(employeeCurrentSalary);
        }
    }
}
